### ISSUE TITLE
[Feature] 계산기(Calculator)

### ISSUE THREAD

**Issue by sdhong0609** [sdhong0609/carbon-calculator#3]
## Overview
1. 메인화면 첫번째 탭 : 계산기(Calculator) 화면 및 로직 구현
2. 세로로 스크롤 가능한 화면으로 진행 : 만약 UI 요소가 너무 많이 들어간다면 화면 분할도 고려
## Todo
1. 사용방법 설명 화면
- [x] 탄소발자국 계산기에 대한 설명과 사용방법 설명
- [x] 사용방법 설명 화면에서 입력할 항목 체크 가능
- [x] 계산기 시작 버튼 누르면 계산기 화면으로 이동
- [x] 아무런 계산기 항목에도 체크하지 않으면 최소한 하나는 체크해야 한다는 Snackbar 표시

2. 계산기 화면
- [x] 계산기 화면에서 사용방법 설명 화면에서 체크한 항목만 입력 가능
- [x] 전기 사용량, 가스 사용량, 수도 사용량, 생활 폐기물 입력
- [x] 초기화버튼 누르면 입력한 숫자 모두 초기화
- [x] 결과 보기 버튼 누르면 계산 결과 화면으로 이동

3. 계산 결과 화면
- [x] 총 탄소배출량 표시
