### ISSUE TITLE
[Feature] 계산기 화면의 버튼 전부 하단으로 이동

### ISSUE THREAD

**Issue by sdhong0609** [sdhong0609/carbon-calculator#9]
## Overview
계산기 화면의 버튼 전부 하단으로 이동
## Todo
- [x] 하나의 버튼 기반의 Screen Composable 함수 정의
- [x] 두 개의 버튼 기반의 Screen Composable 함수 정의
- [x] 계산기 설명 화면, 계산기 화면, 계산 결과 화면에 각각 적용하여 버튼 전부 하단으로 이동
